### ISSUE TITLE
macro filter_exceptions calls columns that are not avalailable

### ISSUE THREAD

**Issue by jschintz-windriver** [dbt-labs/dbt-project-evaluator#381]
### Describe the bug
When upgrading from v0.6.1 to v0.7.2 we encountered the following error.

```
ERROR creating sql table model dbt_cloud_pr_211000_305.fct_direct_join_to_source
000904 (42000): SQL compilation error: error line 58 at position 20
invalid identifier 'PARENT_DIRECTORY_PATH'
compiled Code at target/run/dbt_project_evaluator/models/marts/dag/fct_direct_join_to_source.sql
```

### Steps to reproduce
Line 45 of fct_direct_join_to_source called a macro '{{ filter_exceptions(model.name) }}'
This macro compiled to 
`where 1=1 and parent_directory_path = 'XXXX'`

But, the field parent_directory_path is not available in upstream 'final' cte

### Expected results
all models should execute in package

### Actual results
not all models could run in package

### System information
**The contents of your `packages.yml` file:**
  - package: dbt-labs/dbt_project_evaluator
    version: 0.7.3

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
1.6

### Are you interested in contributing the fix?
Sure!  Anything I can do to help

**Comment by b-per** [comment]
Thanks for raising the issue.

Have you overwritten the macro `filter_exceptions()` in your project? I can't seem to see where `where 1=1 and parent_directory_path = 'XXXX'` could come from.

**Comment by jschintz-windriver** [comment]
Thanks for the quick response - no overrides
I was using your published package - not even a fork.  You've been making such good stuff we want the latest :)

**Comment by b-per** [comment]
OK, then the issue might be due to the exceptions CSV file you have in place. `fct_direct_join_to_source.sql` was updated lately to remove some columns and your exception file might still refer to an older columns that was removed.

**Comment by jschintz-windriver** [comment]
Gotcha!  That was it.
Really appreciate the help.
